"""Local non-executing integration advisory APIs for MVP-0.

Importing this package performs no runtime initialization, reads no files,
writes no files, executes no commands, calls no network, and mutates no Git.
"""

from .commit_candidate_renderer import (
    AcceptedOutputItem,
    AcceptedOutputRegister,
    CommitCandidate,
    CommitCommandBlock,
    DriftItem,
    DriftRegister,
    GitAdvisory,
    IntegrationRenderRequest,
    IntegrationSummary,
    PushInstruction,
    RejectedOutputItem,
    RejectedOutputRegister,
    RollbackNote,
    build_accepted_output_register,
    build_commit_candidate,
    build_commit_command_block,
    build_drift_register,
    build_git_advisory,
    build_integration_summary,
    build_rejected_output_register,
    render_accepted_output_register,
    render_drift_register,
    render_integration_summary,
    render_rejected_output_register,
)

__all__ = (
    "AcceptedOutputItem",
    "AcceptedOutputRegister",
    "CommitCandidate",
    "CommitCommandBlock",
    "DriftItem",
    "DriftRegister",
    "GitAdvisory",
    "IntegrationRenderRequest",
    "IntegrationSummary",
    "PushInstruction",
    "RejectedOutputItem",
    "RejectedOutputRegister",
    "RollbackNote",
    "build_accepted_output_register",
    "build_commit_candidate",
    "build_commit_command_block",
    "build_drift_register",
    "build_git_advisory",
    "build_integration_summary",
    "build_rejected_output_register",
    "render_accepted_output_register",
    "render_drift_register",
    "render_integration_summary",
    "render_rejected_output_register",
)
