"""Public API for the P15.7 single-worker controlled gate."""

from __future__ import annotations

from hermes_cli.agent_platform.provider_worker_gate.contracts import (
    GOVERNED_CREDENTIAL_LEASE_TTL_MS,
    GOVERNED_CREDENTIAL_MINIMUM_REMAINING_LIFETIME_MS,
    MAXIMUM_RESPONSES_CREATE_CALLS,
    OPENAI_CODEX_AUTHENTICATION,
    OPENAI_CODEX_CREDENTIAL_STORE_ID,
    OPENAI_CODEX_ENDPOINT,
    OPENAI_CODEX_MODEL_ID,
    OPENAI_CODEX_P15_7_EXPECTED_OUTPUT,
    OPENAI_CODEX_P15_7_SYSTEM_INSTRUCTION,
    OPENAI_CODEX_PROVIDER,
    OPENAI_CODEX_PROVIDER_ACCOUNTING_POLICY_ID,
    OPENAI_CODEX_PROVIDER_FAILURE_POLICY_ID,
    OPENAI_CODEX_PROVIDER_RUNTIME_PROFILE_ID,
    OPENAI_CODEX_PROVIDER_WORKER_GATE_ID,
    OPENAI_CODEX_PROVIDER_WORKER_PROFILE_ID,
    OPENAI_CODEX_REASONING_EFFORT,
    OPENAI_CODEX_REASONING_SUMMARY,
    OPENAI_CODEX_SINGLE_DISPATCH_EVENT_CONSUMER,
    OPENAI_CODEX_TRANSPORT,
    PROVIDER_WORKER_GATE_SCHEMA_VERSION,
    SDK_MAX_RETRIES,
    WORKER_FALLBACK_ATTEMPTS,
    WORKER_RETRY_ATTEMPTS,
    ProviderWorkerGateDispatchEvidence,
    ProviderWorkerGateDiagnostics,
    ProviderWorkerGatePolicy,
    ProviderWorkerGateRequest,
    ProviderWorkerGateResult,
)
from hermes_cli.agent_platform.provider_worker_gate.runtime import (
    ProviderWorkerGateRuntimeError,
    create_openai_codex_client,
    run_controlled_worker_payload,
    run_controlled_worker_request,
    run_worker_stdio,
)
from hermes_cli.agent_platform.provider_worker_gate.single_dispatch import (
    assert_canonical_codex_backend_create_kwargs,
    build_codex_responses_create_kwargs,
    build_provider_worker_gate_request,
    build_usage_record_id,
    run_openai_codex_single_dispatch,
)


__all__ = [
    "GOVERNED_CREDENTIAL_LEASE_TTL_MS",
    "GOVERNED_CREDENTIAL_MINIMUM_REMAINING_LIFETIME_MS",
    "MAXIMUM_RESPONSES_CREATE_CALLS",
    "OPENAI_CODEX_AUTHENTICATION",
    "OPENAI_CODEX_CREDENTIAL_STORE_ID",
    "OPENAI_CODEX_ENDPOINT",
    "OPENAI_CODEX_MODEL_ID",
    "OPENAI_CODEX_P15_7_EXPECTED_OUTPUT",
    "OPENAI_CODEX_P15_7_SYSTEM_INSTRUCTION",
    "OPENAI_CODEX_PROVIDER",
    "OPENAI_CODEX_PROVIDER_ACCOUNTING_POLICY_ID",
    "OPENAI_CODEX_PROVIDER_FAILURE_POLICY_ID",
    "OPENAI_CODEX_PROVIDER_RUNTIME_PROFILE_ID",
    "OPENAI_CODEX_PROVIDER_WORKER_GATE_ID",
    "OPENAI_CODEX_PROVIDER_WORKER_PROFILE_ID",
    "OPENAI_CODEX_REASONING_EFFORT",
    "OPENAI_CODEX_REASONING_SUMMARY",
    "OPENAI_CODEX_SINGLE_DISPATCH_EVENT_CONSUMER",
    "OPENAI_CODEX_TRANSPORT",
    "PROVIDER_WORKER_GATE_SCHEMA_VERSION",
    "SDK_MAX_RETRIES",
    "WORKER_FALLBACK_ATTEMPTS",
    "WORKER_RETRY_ATTEMPTS",
    "ProviderWorkerGateDispatchEvidence",
    "ProviderWorkerGateDiagnostics",
    "ProviderWorkerGatePolicy",
    "ProviderWorkerGateRequest",
    "ProviderWorkerGateResult",
    "ProviderWorkerGateRuntimeError",
    "assert_canonical_codex_backend_create_kwargs",
    "build_codex_responses_create_kwargs",
    "build_provider_worker_gate_request",
    "build_usage_record_id",
    "create_openai_codex_client",
    "run_controlled_worker_payload",
    "run_controlled_worker_request",
    "run_openai_codex_single_dispatch",
    "run_worker_stdio",
]
