"""Public contract API for AGENT PLATFORM provider credentials."""

from __future__ import annotations

from hermes_cli.agent_platform.provider_credentials.contracts import (
    MAX_ACTIVE_PROVIDER_CREDENTIAL_LEASES,
    MAX_PROVIDER_CREDENTIAL_LEASE_TTL_MS,
    MIN_PROVIDER_CREDENTIAL_REMAINING_LIFETIME_MS,
    OPENAI_CODEX_CREDENTIAL_STORE_ID,
    OPENAI_CODEX_HERMES_PROVIDER_ID,
    OPENAI_CODEX_INTERNAL_LABEL,
    OPENAI_CODEX_PROVIDER_ENDPOINT,
    PROVIDER_CLIENT_TOKEN_REMOTE_VALIDITY,
    PROVIDER_CREDENTIAL_REMOTE_REVOCATION_STATUS,
    PROVIDER_CREDENTIAL_SCHEMA_VERSION,
    OpenAICodexOAuthCredential,
    ProviderClientTokenStatus,
    ProviderCredentialAcquisitionPlan,
    ProviderCredentialAcquisitionResult,
    ProviderCredentialAuthKind,
    ProviderCredentialDeliveryLease,
    ProviderCredentialLeaseCleanup,
    ProviderCredentialLocalClearResult,
    ProviderCredentialProvider,
    ProviderCredentialRef,
    ProviderCredentialStatus,
)

__all__ = [
    "MAX_ACTIVE_PROVIDER_CREDENTIAL_LEASES",
    "MAX_PROVIDER_CREDENTIAL_LEASE_TTL_MS",
    "MIN_PROVIDER_CREDENTIAL_REMAINING_LIFETIME_MS",
    "OPENAI_CODEX_CREDENTIAL_STORE_ID",
    "OPENAI_CODEX_HERMES_PROVIDER_ID",
    "OPENAI_CODEX_INTERNAL_LABEL",
    "OPENAI_CODEX_PROVIDER_ENDPOINT",
    "PROVIDER_CLIENT_TOKEN_REMOTE_VALIDITY",
    "PROVIDER_CREDENTIAL_REMOTE_REVOCATION_STATUS",
    "PROVIDER_CREDENTIAL_SCHEMA_VERSION",
    "OpenAICodexOAuthCredential",
    "ProviderClientTokenStatus",
    "ProviderCredentialAcquisitionPlan",
    "ProviderCredentialAcquisitionResult",
    "ProviderCredentialAuthKind",
    "ProviderCredentialDeliveryLease",
    "ProviderCredentialLeaseCleanup",
    "ProviderCredentialLocalClearResult",
    "ProviderCredentialProvider",
    "ProviderCredentialRef",
    "ProviderCredentialStatus",
]
