"""Planning-only Ticket Factory contracts."""

from hermes_cli.agent_platform.ticket_factory.context_packs import (
    CONTEXT_PACK_SCHEMA_VERSION,
    ContextAssemblyPolicy,
    ContextAssemblyRequest,
    ContextPack,
    ContextPackAssemblyError,
    ContextPackBudgetError,
    ContextPackItem,
    ContextPackSensitiveContentError,
    ContextPriority,
    ContextSensitivity,
    ContextSourceKind,
    ContextSourceSpec,
    OptionalSourceOverflowStrategy,
    assemble_context_pack,
)

from hermes_cli.agent_platform.ticket_factory.generator_roles import (
    TICKET_GENERATOR_ROLE_SCHEMA_VERSION,
    GeneratorAssignment,
    GeneratorRoleProfile,
    TicketGenerationRequest,
    TicketGeneratorCompatibilityError,
    TicketGeneratorRole,
    TicketGeneratorRoleError,
    TicketProposal,
    TicketProposalValidationError,
    build_ticket_proposal,
    get_ticket_generator_role_profile,
    list_ticket_generator_role_profiles,
    prepare_ticket_generator_assignments,
    validate_ticket_generator_proposal,
)

from hermes_cli.agent_platform.ticket_factory.specs import (
    PROJECT_SPEC_SCHEMA_VERSION,
    TICKET_SPEC_SCHEMA_VERSION,
    AuthorityReferenceKind,
    AuthorityReferenceSpec,
    DependencyKind,
    DependencyScope,
    ParallelizationHint,
    ProjectSpec,
    RepositoryScopeSpec,
    TicketDependencySpec,
    TicketResponseContractSpec,
    TicketSpec,
    TicketType,
    TicketValidationStepSpec,
)

__all__ = (
    "PROJECT_SPEC_SCHEMA_VERSION",
    "TICKET_SPEC_SCHEMA_VERSION",
    "CONTEXT_PACK_SCHEMA_VERSION",
    "TicketType",
    "DependencyKind",
    "DependencyScope",
    "ParallelizationHint",
    "AuthorityReferenceKind",
    "ContextSourceKind",
    "ContextSensitivity",
    "ContextPriority",
    "OptionalSourceOverflowStrategy",
    "AuthorityReferenceSpec",
    "TicketDependencySpec",
    "RepositoryScopeSpec",
    "TicketValidationStepSpec",
    "TicketResponseContractSpec",
    "ProjectSpec",
    "TicketSpec",
    "ContextSourceSpec",
    "ContextAssemblyPolicy",
    "ContextAssemblyRequest",
    "ContextPackItem",
    "ContextPack",
    "ContextPackAssemblyError",
    "ContextPackBudgetError",
    "ContextPackSensitiveContentError",
    "assemble_context_pack",
    "TICKET_GENERATOR_ROLE_SCHEMA_VERSION",
    "TicketGeneratorRole",
    "GeneratorRoleProfile",
    "TicketGenerationRequest",
    "GeneratorAssignment",
    "TicketProposal",
    "TicketGeneratorRoleError",
    "TicketGeneratorCompatibilityError",
    "TicketProposalValidationError",
    "get_ticket_generator_role_profile",
    "list_ticket_generator_role_profiles",
    "prepare_ticket_generator_assignments",
    "build_ticket_proposal",
    "validate_ticket_generator_proposal",
)
