"""Public contract API for AGENT PLATFORM provider accounting."""

from __future__ import annotations

from hermes_cli.agent_platform.provider_accounting.accounting import (
    ProviderAccountingError,
    build_subscription_included_cost,
    build_timeout_accounting,
    create_provider_accounting_record,
    normalize_codex_app_server_usage,
    normalize_codex_responses_usage,
    validate_worker_result_accounting_link,
)
from hermes_cli.agent_platform.provider_accounting.contracts import (
    OPENAI_CODEX_BILLING_MODE,
    OPENAI_CODEX_PROVIDER_ACCOUNTING_POLICY_ID,
    OPENAI_CODEX_PROVIDER_MODEL_ID,
    OPENAI_CODEX_PROVIDER_RUNTIME_PROFILE_ID,
    OPENAI_CODEX_PROVIDER_WORKER_PROFILE_ID,
    PROVIDER_ACCOUNTING_SCHEMA_VERSION,
    ProviderAccountingPolicy,
    ProviderAccountingRecord,
    ProviderAccountingWorkerResultLink,
    ProviderCostAccounting,
    ProviderTimeoutAccounting,
    ProviderTimeoutBudget,
    ProviderUsageCounters,
    ProviderUsageEvidence,
)
from hermes_cli.agent_platform.provider_accounting.enums import (
    ProviderAccountingLinkState,
    ProviderAccountingOutcome,
    ProviderCostSource,
    ProviderCostStatus,
    ProviderTimeoutDisposition,
    ProviderTimeoutStage,
    ProviderUsageCompleteness,
    ProviderUsageSource,
)

__all__ = [
    "PROVIDER_ACCOUNTING_SCHEMA_VERSION",
    "OPENAI_CODEX_PROVIDER_ACCOUNTING_POLICY_ID",
    "OPENAI_CODEX_PROVIDER_RUNTIME_PROFILE_ID",
    "OPENAI_CODEX_PROVIDER_WORKER_PROFILE_ID",
    "OPENAI_CODEX_PROVIDER_MODEL_ID",
    "OPENAI_CODEX_BILLING_MODE",
    "ProviderUsageSource",
    "ProviderUsageCompleteness",
    "ProviderCostStatus",
    "ProviderCostSource",
    "ProviderTimeoutStage",
    "ProviderAccountingOutcome",
    "ProviderTimeoutDisposition",
    "ProviderAccountingLinkState",
    "ProviderAccountingPolicy",
    "ProviderUsageCounters",
    "ProviderUsageEvidence",
    "ProviderCostAccounting",
    "ProviderTimeoutBudget",
    "ProviderTimeoutAccounting",
    "ProviderAccountingRecord",
    "ProviderAccountingWorkerResultLink",
    "ProviderAccountingError",
    "normalize_codex_responses_usage",
    "normalize_codex_app_server_usage",
    "build_subscription_included_cost",
    "build_timeout_accounting",
    "create_provider_accounting_record",
    "validate_worker_result_accounting_link",
]
