"""Public API for governed provider failure and retry policy."""

from __future__ import annotations

from hermes_cli.agent_platform.provider_failure_policy.contracts import (
    MAXIMUM_RETRY_AFTER_MS,
    PROVIDER_FAILURE_AUTHENTICATION,
    PROVIDER_FAILURE_ENDPOINT,
    PROVIDER_FAILURE_POLICY_ID,
    PROVIDER_FAILURE_POLICY_SCHEMA_VERSION,
    PROVIDER_FAILURE_PROVIDER,
    PROVIDER_FAILURE_TRANSPORT,
    ProviderFailureAccountingLink,
    ProviderFailureAccountingProjection,
    ProviderFailureClassification,
    ProviderFailurePolicy,
    ProviderFailureRecord,
    ProviderFailureSignal,
    ProviderRetryDecision,
)
from hermes_cli.agent_platform.provider_failure_policy.enums import (
    ProviderFailureAccountingLinkState,
    ProviderFailureCategory,
    ProviderFailureOrigin,
    ProviderFailureStage,
    ProviderRecoveryAction,
    ProviderRetryDelaySource,
    ProviderRetryDisposition,
    ProviderSDKExceptionKind,
)
from hermes_cli.agent_platform.provider_failure_policy.policy import (
    build_failure_record_id,
    build_provider_failure_record,
    build_provider_retry_decision,
    classify_openai_codex_failure,
    project_failure_to_accounting,
    resolve_safe_failure_summary,
    validate_failure_accounting_link,
)

__all__ = [
    "PROVIDER_FAILURE_POLICY_SCHEMA_VERSION",
    "PROVIDER_FAILURE_POLICY_ID",
    "PROVIDER_FAILURE_PROVIDER",
    "PROVIDER_FAILURE_AUTHENTICATION",
    "PROVIDER_FAILURE_ENDPOINT",
    "PROVIDER_FAILURE_TRANSPORT",
    "MAXIMUM_RETRY_AFTER_MS",
    "ProviderFailureCategory",
    "ProviderFailureStage",
    "ProviderFailureOrigin",
    "ProviderRetryDisposition",
    "ProviderRecoveryAction",
    "ProviderRetryDelaySource",
    "ProviderSDKExceptionKind",
    "ProviderFailureAccountingLinkState",
    "ProviderFailurePolicy",
    "ProviderFailureSignal",
    "ProviderFailureClassification",
    "ProviderFailureRecord",
    "ProviderRetryDecision",
    "ProviderFailureAccountingProjection",
    "ProviderFailureAccountingLink",
    "build_failure_record_id",
    "classify_openai_codex_failure",
    "build_provider_failure_record",
    "build_provider_retry_decision",
    "project_failure_to_accounting",
    "validate_failure_accounting_link",
    "resolve_safe_failure_summary",
]
