"""Inert MVP-0 skeleton package for AGENT PLATFORM.

Importing this package performs no runtime initialization, reads no files,
writes no files, executes no commands, calls no network, and mutates no Git.
"""

from .boundary import DEFAULT_MVP0_BOUNDARY_POLICY, Mvp0BoundaryPolicy
from .contracts import (
    AcceptedOutputRegisterRef,
    AuditRef,
    BoundaryRef,
    CommitCandidateRef,
    CommitCommandBlockRef,
    ContextRef,
    DriftRegisterRef,
    EvidenceRef,
    HarnessInputPackageDraftRef,
    HarnessOutputPackageRef,
    HumanApprovalRef,
    IncidentRef,
    IntegrationChecklistRef,
    MemoryRef,
    Mvp0ActivationLevel,
    Mvp0BlockedReason,
    Mvp0OperationResult,
    Mvp0OperationStatus,
    Mvp0ReviewStatus,
    Mvp0SessionEnvelope,
    Mvp0SurfaceKind,
    RejectedOutputRegisterRef,
    RetentionRef,
    ReviewChecklistRef,
    RollbackRef,
    UserObjectiveEnvelope,
    WorkPacketDraftRef,
)
from .noop import (
    BlockedMvp0Operation,
    build_blocked_result,
    build_metadata_only_result,
    build_needs_human_review_result,
)
from .package import NoOpMvp0Package

__all__ = (
    "AcceptedOutputRegisterRef",
    "AuditRef",
    "BlockedMvp0Operation",
    "BoundaryRef",
    "CommitCandidateRef",
    "CommitCommandBlockRef",
    "ContextRef",
    "DEFAULT_MVP0_BOUNDARY_POLICY",
    "DriftRegisterRef",
    "EvidenceRef",
    "HarnessInputPackageDraftRef",
    "HarnessOutputPackageRef",
    "HumanApprovalRef",
    "IncidentRef",
    "IntegrationChecklistRef",
    "MemoryRef",
    "Mvp0ActivationLevel",
    "Mvp0BlockedReason",
    "Mvp0BoundaryPolicy",
    "Mvp0OperationResult",
    "Mvp0OperationStatus",
    "Mvp0ReviewStatus",
    "Mvp0SessionEnvelope",
    "Mvp0SurfaceKind",
    "NoOpMvp0Package",
    "RejectedOutputRegisterRef",
    "RetentionRef",
    "ReviewChecklistRef",
    "RollbackRef",
    "UserObjectiveEnvelope",
    "WorkPacketDraftRef",
    "build_blocked_result",
    "build_metadata_only_result",
    "build_needs_human_review_result",
)
