"""Public contract API for the governed AGENT PLATFORM runtime adapter."""

from __future__ import annotations

from hermes_cli.agent_platform.runtime_adapter.contracts import (
    HERMES_DASHBOARD_EXPERIMENTAL_PROFILE_ID,
    RUNTIME_ADAPTER_CONTRACT_SCHEMA_VERSION,
    TEST_LIFECYCLE_PROBE_PROFILE_ID,
    RuntimeCancelRequest,
    RuntimeEvent,
    RuntimeEvidenceRef,
    RuntimeFailure,
    RuntimeHandle,
    RuntimeLaunchRequest,
    RuntimeLogRef,
    RuntimeOperationResult,
    RuntimeProcessRef,
    RuntimeProfileRef,
    RuntimeReadinessRef,
    RuntimeRollbackRequest,
    RuntimeStopRequest,
    RuntimeTimeoutPolicy,
    RuntimeWorkspaceBinding,
    RuntimeWorkspaceRef,
)
from hermes_cli.agent_platform.runtime_adapter.enums import (
    RuntimeCleanupStatus,
    RuntimeEventType,
    RuntimeFailureStage,
    RuntimeLifecycleAction,
    RuntimeLifecycleState,
    RuntimeLogStream,
    RuntimeOperationOutcome,
    RuntimeProcessStatus,
    RuntimeProfileClass,
    RuntimeReadinessState,
    RuntimeRetentionPolicy,
    RuntimeRetryability,
    RuntimeSeverity,
    RuntimeWorkspaceStatus,
)
from hermes_cli.agent_platform.runtime_adapter.errors import (
    InvalidRuntimeTransitionError,
    RuntimeAdapterContractError,
    RuntimeContractValidationError,
)
from hermes_cli.agent_platform.runtime_adapter.state_machine import (
    allowed_runtime_actions,
    is_runtime_terminal,
    transition_runtime_state,
)

__all__ = [
    "HERMES_DASHBOARD_EXPERIMENTAL_PROFILE_ID",
    "RUNTIME_ADAPTER_CONTRACT_SCHEMA_VERSION",
    "TEST_LIFECYCLE_PROBE_PROFILE_ID",
    "InvalidRuntimeTransitionError",
    "RuntimeAdapterContractError",
    "RuntimeCancelRequest",
    "RuntimeCleanupStatus",
    "RuntimeContractValidationError",
    "RuntimeEvent",
    "RuntimeEventType",
    "RuntimeEvidenceRef",
    "RuntimeFailure",
    "RuntimeFailureStage",
    "RuntimeHandle",
    "RuntimeLaunchRequest",
    "RuntimeLifecycleAction",
    "RuntimeLifecycleState",
    "RuntimeLogRef",
    "RuntimeLogStream",
    "RuntimeOperationOutcome",
    "RuntimeOperationResult",
    "RuntimeProcessRef",
    "RuntimeProcessStatus",
    "RuntimeProfileClass",
    "RuntimeProfileRef",
    "RuntimeReadinessRef",
    "RuntimeReadinessState",
    "RuntimeRetentionPolicy",
    "RuntimeRetryability",
    "RuntimeRollbackRequest",
    "RuntimeSeverity",
    "RuntimeStopRequest",
    "RuntimeTimeoutPolicy",
    "RuntimeWorkspaceBinding",
    "RuntimeWorkspaceRef",
    "RuntimeWorkspaceStatus",
    "allowed_runtime_actions",
    "is_runtime_terminal",
    "transition_runtime_state",
]
